services:
  nextjs:
    image: ghcr.io/oppenheimor/qiaopi-generator-nextjs:latest
    container_name: qiaopi-generator-nextjs
    restart: always
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production

networks:
  app-network:
    external: true
